# Generated by Django 6.0 on 2025-12-31 08:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('icon', models.ImageField(upload_to='servicebox/')),
                ('title_en', models.CharField(max_length=50)),
                ('title_mm', models.CharField(max_length=50)),
                ('des_en', models.TextField()),
                ('des_mm', models.TextField()),
                ('service_list_en', models.JSONField(default=list)),
                ('service_list_mm', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
