# Generated by Django 6.0 on 2025-12-31 09:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_servicebox'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_num', models.IntegerField()),
                ('project_title', models.CharField(max_length=50)),
                ('project_des', models.TextField()),
                ('project_link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
