# Generated by Django 5.2.7 on 2026-01-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contactus_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectbox',
            name='project_des',
        ),
        migrations.RemoveField(
            model_name='projectbox',
            name='project_title',
        ),
        migrations.AddField(
            model_name='projectbox',
            name='project_des_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectbox',
            name='project_des_mm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectbox',
            name='project_title_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectbox',
            name='project_title_mm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
