# Generated by Django 5.2.7 on 2026-01-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_projectbox_project_des_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_des',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_title',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_des_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_des_mm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_title_mm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
